language: node_js
node_js:
  - 14
cache: npm
notifications:
  email: false
script:
  - npm run lint
  - npm run test
  - make ci
after_success:
  - npm install -g codecov
  - npm t # running tests again technically, but only after a successful build already to generate code cov reports
  - codecov
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
